services:
  - type: worker
    name: fb-downloader-bot
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false